### ISSUE TITLE
ImportError: No module named dataset_loaders.images.camvid

### ISSUE THREAD

**Issue by kuixu** [SimJeg/FC-DenseNet#1]
Looking forward to the dataset_loaders.

```
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from data_loader import load_data
  File "/data/kuixu/exper/fcn/FC-DenseNet/data_loader.py", line 1, in <module>
    from dataset_loaders.images.camvid import CamvidDataset
ImportError: No module named dataset_loaders.images.camvid
```

**Comment by SimJeg** [comment]
Hi Barryjui,

I updated the README to answer your question.
Unfortunately, we can't release the data loader immediately, but if you do want to run the code now you can follow the indications of the paragraph "Data".

**Comment by kuixu** [comment]
@SimJeg Thanks for your detailed description of the dataset loader so that I can repeat it.

**Comment by amiltonwong** [comment]
Hi, @barrykui ,

Did you work out the dataset_loaders? If yes, could you release it on-line?

THX~

**Comment by rozefeld** [comment]
Hello.

I am trying to apply your network on my data. 
It is stated in README.md that "X is the batch of input images (shape= (batch_size, n_classes, n_rows, n_cols), dtype=float32) " 
My quwstion is: shouldn't it be shape= (batch_size, 3, n_rows, n_cols), dtype=float32, a.k.a. THREE color channels?

Thank you

**Comment by SimJeg** [comment]
Yes you're right! Sorry for the typo

**Comment by qiaotian** [comment]
Hello,

I'm also trying to use this network, but I got some errors after I implemented my own Iterator. The last several lines are listed as follows:

> TypeError: Cannot convert Type TensorType(float64, 4D) (of Variable AbstractConv2d_gradInputs{border_mode='half', subsample=(1, 1), filter_flip=False, imshp=(None, 3, None, None), kshp=(48, 3, 3, 3)}.0) into Type TensorType(float32, 4D). You can try to manually convert AbstractConv2d_gradInputs{border_mode='half', subsample=(1, 1), filter_flip=False, imshp=(None, 3, None, None), kshp=(48, 3, 3, 3)}.0 into a TensorType(float32, 4D).

Does anyone meet this before?
Any clue will be greatly appreciated.

**Comment by SimJeg** [comment]
It seems you have to cast your data in float32 (by default it's float64)

Le 4 févr. 2017 16:45, "Tien" <notifications@github.com> a écrit :

Hello,

I'm also trying to use your network, but I got some errors after I
implement my own Iterator. The last several lines are listed as follows:

TypeError: Cannot convert Type TensorType(float64, 4D) (of Variable
AbstractConv2d_gradInputs{border_mode='half', subsample=(1, 1),
filter_flip=False, imshp=(None, 3, None, None), kshp=(48, 3, 3, 3)}.0) into
Type TensorType(float32, 4D). You can try to manually convert
AbstractConv2d_gradInputs{border_mode='half', subsample=(1, 1),
filter_flip=False, imshp=(None, 3, None, None), kshp=(48, 3, 3, 3)}.0 into
a TensorType(float32, 4D).

Does anyone meet this before?
Any clue will be greatly appreciated.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/SimJeg/FC-DenseNet/issues/1#issuecomment-277454119>,
or mute
the thread

**Comment by qiaotian** [comment]
Thanks a lot !!!
It seems to work when I add 'floatX=float32' to THEANO_FLAGS.

**Comment by qiaotian** [comment]
Hi, @SimJeg . I encounter another problem, which I tried my best but failed to solve.

I test my own dataset on this network.
But, it always returns the **CNMEM_STATUS_OUT_OF_MEMORY** message when excuting `loss, I, U, acc = f(X, Y[:, None, :, :])` inside `batch_loop` function.
It is not clear to me whether this error is caused by the illegal iterator, the large intermediate values or theano limitations. Looking forward to your reply.

PS. My GPU is one piece of Titan X Maxwell (12GB mem). 

The **.theanorc** and **error message** are provided as follows:
1. '.theanorc' file content:

> [global]
floatX = float32
device = gpu2
optimizer = fast_compile
optimizer_including = fusion
allow_gc = True
print_active_device = True
optimizer_including = cudnn
[lib]
cnmem = 0.8
[dnn]
enabled = True

2. Error message:

> .....
Number of Convolutional layers : 103
Number of parameters : 9426191
Compilation starts at 2017-02-06 11:49:04
train compilation took **620.547** seconds
valid compilation took **152.227** seconds
Training starts at 2017-02-06 12:02:04
Traceback (most recent call last):
  File "train.py", line 307, in <module>
    initiate_training(cf)
  File "train.py", line 276, in initiate_training
    train(cf)
  File "train.py", line 198, in train
    history = batch_loop(train_iter, train_fn, epoch, 'train', history)
  File "train.py", line 89, in batch_loop
    loss, I, U, acc = f(X, Y[:, None, :, :])
  File "/home/qiao/anaconda2/envs/tensorflow/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/qiao/anaconda2/envs/tensorflow/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/qiao/anaconda2/envs/tensorflow/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
MemoryError: Error allocating **503316480** bytes of device memory (**CNMEM_STATUS_OUT_OF_MEMORY**).
Apply node that caused the error: GpuElemwise{mul,no_inplace}(CudaNdarrayConstant{[[[[ 0.5]]]]}, GpuElemwise{add,no_inplace}.0)
Toposort index: 5298
Inputs types: [CudaNdarrayType(float32, (True, True, True, True)), CudaNdarrayType(float32, 4D)]
Inputs shapes: [(1, 1, 1, 1), (5, 96, 512, 512)]
Inputs strides: [(0, 0, 0, 0), (25165824, 262144, 512, 1)]
Inputs values: [CudaNdarray([[[[ 0.5]]]]), 'not shown']
Outputs clients: [[GpuContiguous(GpuElemwise{mul,no_inplace}.0)]]

> HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by SimJeg** [comment]
Hi, can you try to set cnmem=1 in your theanorc? cnmem=0.8 means you only
use 80% of your GPU's memory



Le 6 févr. 2017 05:42, "Tien" <notifications@github.com> a écrit :

Hi, @SimJeg <https://github.com/SimJeg> . I encounter another problem,
which I tried my best but failed to solve.

I test my own dataset on this network.
But, it always returns the *CNMEM_STATUS_OUT_OF_MEMORY* message when
excuting loss, I, U, acc = f(X, Y[:, None, :, :]) inside batch_loop
function.
It is not clear to me whether this error is caused by the illegal iterator,
the large intermediate values or theano limitations. Looking forward to
your reply.

PS. My GPU is one piece of Titan X Maxwell (12GB mem).

The *.theanorc* and *error message* are provided as follows:

   1. '.theanorc' file content:

[global]
floatX = float32
device = gpu2
optimizer = fast_compile
optimizer_including = fusion
allow_gc = True
print_active_device = True
optimizer_including = cudnn
[lib]
cnmem = 0.8
[dnn]
enabled = True


   1. Error message:

.....
Number of Convolutional layers : 103
Number of parameters : 9426191
Compilation starts at 2017-02-06 11:49:04
train compilation took *620.547* seconds
valid compilation took *152.227* seconds
Training starts at 2017-02-06 12:02:04

Traceback (most recent call last):
File "train.py", line 307, in
initiate_training(cf)
File "train.py", line 276, in initiate_training
train(cf)
File "train.py", line 198, in train
history = batch_loop(train_iter, train_fn, epoch, 'train', history)
File "train.py", line 89, in batch_loop
loss, I, U, acc = f(X, Y[:, None, :, :])
File "/home/qiao/anaconda2/envs/tensorflow/lib/python2.7/site-
packages/theano/compile/function_module.py", line 871, in *call*
storage_map=getattr(self.fn, 'storage_map', None))
File "/home/qiao/anaconda2/envs/tensorflow/lib/python2.7/site-packages/theano/gof/link.py",
line 314, in raise_with_op
reraise(exc_type, exc_value, exc_trace)
File "/home/qiao/anaconda2/envs/tensorflow/lib/python2.7/site-
packages/theano/compile/function_module.py", line 859, in *call*
outputs = self.fn()
MemoryError: Error allocating *503316480* bytes of device memory (
*CNMEM_STATUS_OUT_OF_MEMORY*).
Apply node that caused the error:
GpuElemwise{mul,no_inplace}(CudaNdarrayConstant{[[[[
0.5]]]]}, GpuElemwise{add,no_inplace}.0)
Toposort index: 5298
Inputs types: [CudaNdarrayType(float32, (True, True, True, True)),
CudaNdarrayType(float32, 4D)]
Inputs shapes: [(1, 1, 1, 1), (5, 96, 512, 512)]
Inputs strides: [(0, 0, 0, 0), (25165824, 262144, 512, 1)]
Inputs values: [CudaNdarray([[[[ 0.5]]]]), 'not shown']
Outputs clients: [[GpuContiguous(GpuElemwise{mul,no_inplace}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a
back-trace of when this node was created. This can be done with by setting
the Theano flag 'optimizer=fast_compile'. If that does not work, Theano
optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and
storage map footprint of this apply node.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/SimJeg/FC-DenseNet/issues/1#issuecomment-277585514>,
or mute
the thread

**Comment by qiaotian** [comment]
Thanks for your suggestion. But the error remains even if I changed the cnmem to 1. I looked up more docs and found out the following two that might make sense.

> According to [danlanchen](https://danlanchen.github.io/blog/2016/10/12/training-CNN-error-handling) and [theano official doc](http://deeplearning.net/software/theano/faq.html), the error occurs mainly due to **large number of generated intermediate values** and **fragmented gpu memory**.

Fortunately, the error disappears after decreasing both the network depth and the number of filters.

**Comment by SimJeg** [comment]
Hi, did you try to reduce the batch size / crop size? With crops (224, 224)
you should be able to train with batch size 3, with no crops (None), with
batch size 1.

**Comment by qiaotian** [comment]
@SimJeg 
The error indeed arises from the **big size of input images**. It works well if I crop the raw images in 'batch_loop' manually and then feed these cropped images to the network. 
I should have paid attention to my own training image size (╯□╰).
Thanks again for your kind help.

**Comment by SimJeg** [comment]
You're welcome. Please also note that there is a parameter for cropping in
the config file so you don't need to do it manualy
