### ISSUE TITLE
more confusion about data loaders

### ISSUE THREAD

**Issue by rnunziata** [SimJeg/FC-DenseNet#26]
trying to run test.py
get the following error: I thought data loader would download the data for me...since there is no reference to access the test data on this site.

installed  
   git clone --recursive https://github.com/fvisin/dataset_loaders.git

```
cat /usr/local/lib/python2.7/dist-packages/dataset_loaders-1.0.0-py2.7.egg/dataset_loaders/config.ini
[general]
datasets_local_path = /home/rjn/data

[camvid]
shared_path = /home/rjn/data/camvid/segnet/

[cityscapes]
shared_path = /home/rjn/data/cityscapes/

[kitti]
shared_path = /home/rjn/data/kitti/

[mscoco]
shared_path = /home/rjn/data/COCO/

[pascal_voc]
shared_path = /home/rjn/data/PASCAL-VOC/VOCdevkit/

[scene_parsing_MIT]
shared_path = /home/rjn/data/SceneParsingMIT/

```

error:

```
Unknown arguments: ['get_01c', 'seq_per_video', 'horizontal_flip', 'get_one_hot', 'crop_size']
The local path /home/rjn/data/camvid exist, but is outdated. I will replace the old files with the new ones...
Traceback (most recent call last):
  File "test.py", line 89, in <module>
    test(config_path, weight_path)
  File "test.py", line 30, in test
    _, _, iterator = load_data(cf.dataset, batch_size=batch_size)
  File "/home/rjn/opencv3-p3-code/classification_and_boxing/new_and_abandond/FC-DenseNet/data_loader.py", line 22, in load_data
    rng=rng)
  File "/usr/local/lib/python2.7/dist-packages/dataset_loaders-1.0.0-py2.7.egg/dataset_loaders/images/camvid.py", line 110, in __init__
    super(CamvidDataset, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dataset_loaders-1.0.0-py2.7.egg/dataset_loaders/parallel_loader.py", line 304, in __init__
    shutil.copytree(self.shared_path, self.path)
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: '/home/rjn/data/camvid/segnet/'

```

**Comment by Algebrazebra** [comment]
You need to download the data yourself - the paths in config.ini should point to the base directory of the respective dataset.

**Comment by rnunziata** [comment]
thanks.
